In [1]:
import pandas as pd
from google.colab import drive
import os

# 1. 掛載 Google Drive
drive.mount('/content/drive')

# 2. 根據您的圖片設定精確路徑
# 您的路徑是：MyDrive > Colab Notebooks > 金融與程式設計
base_path = '/content/drive/MyDrive/Colab Notebooks/金融與程式設計/'
input_file = os.path.join(base_path, 資料來源1(作業).csv)
output_file = os.path.join(base_path, '資料來源1_含file欄位_作業版.csv')

# 檢查檔案是否存在
if os.path.exists(input_file):
    print(f"讀取檔案中：{input_file}")

    # 3. 讀取資料
    df = pd.read_csv(input_file)

    # 4. 轉換日期格式並生成 'file (作業)' 欄位
    # 將年月日轉換為 OptionsDaily_YYYY_MM_DD.csv 格式
    df['file (作業)'] = pd.to_datetime(df['年月日']).dt.strftime('OptionsDaily_%Y_%m_%d.csv')

    # 5. 儲存檔案
    # 使用 utf-8-sig 確保 Excel 開啟中文不亂碼
    df.to_csv(output_file, index=False, encoding='utf-8-sig')

    print("-" * 30)
    print(f"✅ 處理完成！")
    print(f"💾 檔案已存於：{output_file}")
    print("-" * 30)

    # 顯示前五筆確認結果
    display(df.head())
else:
    print(f"❌ 找不到檔案！請確認檔案名稱是否為 '資料來源1(作業).csv' 並放置於 {base_path}")

Mounted at /content/drive
❌ 找不到檔案！請確認檔案名稱是否為 '資料來源1(作業).csv' 並放置於 /content/drive/MyDrive/Colab Notebooks/金融與程式設計/

In [2]:
import pandas as pd
from google.colab import drive
import os

# 1. 掛載 Google Drive
drive.mount('/content/drive')

# 2. 設定路徑
base_path = '/content/drive/MyDrive/Colab Notebooks/金融與程式設計/'

# --- 除錯步驟：列出資料夾內所有檔案 ---
print("正在檢查資料夾內容...")
if os.path.exists(base_path):
    files = os.listdir(base_path)
    print(f"資料夾內現有的檔案有：{files}")
else:
    print(f"❌ 找不到路徑：{base_path}，請檢查資料夾名稱是否有誤（例如空格或大小寫）。")

# 3. 嘗試讀取檔案 (加入半形與全形括號的相容性檢查)
target_name = '資料來源1(作業).csv'
input_file = os.path.join(base_path, target_name)

# 如果找不到半形括號，嘗試尋找全形括號檔名
if not os.path.exists(input_file):
    alt_name = '資料來源1（作業）.csv'
    input_file = os.path.join(base_path, alt_name)

if os.path.exists(input_file):
    print(f"✅ 成功找到檔案：{os.path.basename(input_file)}")

    # 讀取資料
    df = pd.read_csv(input_file)

    # 4. 生成 'file (作業)' 欄位
    # 使用 pd.to_datetime 並格式化
    df['file (作業)'] = pd.to_datetime(df['年月日']).dt.strftime('OptionsDaily_%Y_%m_%d.csv')

    # 5. 儲存檔案
    output_file = os.path.join(base_path, '資料來源1_含file欄位_作業版.csv')
    df.to_csv(output_file, index=False, encoding='utf-8-sig')

    print("-" * 30)
    print(f"✅ 處理完成！檔案已存於：{output_file}")
    display(df.head())
else:
    print(f"❌ 依然找不到檔案。請確認雲端硬碟中檔案的精確名稱，並直接修改程式碼中的 target_name。")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
正在檢查資料夾內容...
❌ 找不到路徑：/content/drive/MyDrive/Colab Notebooks/金融與程式設計/，請檢查資料夾名稱是否有誤（例如空格或大小寫）。
❌ 依然找不到檔案。請確認雲端硬碟中檔案的精確名稱，並直接修改程式碼中的 target_name。

In [5]:
import pandas as pd
from google.colab import drive
import os

# 1. 掛載 Google Drive
drive.mount('/content/drive')

# 2. 設定目標檔名 (自動相容全形與半形括號)
target_filename_1 = "資料來源1(作業).csv"
target_filename_2 = "資料來源1（作業）.csv"

print("🔍 正在幫你搜尋檔案，請稍候...")

file_path = None
# 自動搜尋雲端硬碟內的所有資料夾
for root, dirs, files in os.walk('/content/drive/MyDrive/'):
    if target_filename_1 in files:
        file_path = os.path.join(root, target_filename_1)
        break
    elif target_filename_2 in files:
        file_path = os.path.join(root, target_filename_2)
        break

# 3. 執行處理
if file_path:
    print(f"✅ 找到了！路徑是：{file_path}")

    # 讀取檔案，並指定編碼為 'big5' 來處理中文編碼問題
    df = pd.read_csv(file_path, encoding='big5')

    # 處理日期並新增 'file (作業)' 欄位
    # 格式：OptionsDaily_YYYY_MM_DD.csv
    df['file (作業)'] = pd.to_datetime(df['年月日']).dt.strftime('OptionsDaily_%Y_%m_%d.csv')

    # 設定輸出路徑 (放在跟原始檔案同一個資料夾)
    output_path = os.path.join(os.path.dirname(file_path), '資料來源1_含file欄位_作業版.csv')

    # 儲存
    df.to_csv(output_path, index=False, encoding='utf-8-sig')

    print("-" * 30)
    print(f"🎉 處理成功！新檔案已儲存：\n{output_path}")
    display(df.head())
else:
    print("❌ 救命！我翻遍了你的雲端硬碟還是找不到這個檔案。")
    print("請確認檔案是否已經上傳到雲端硬碟，且檔名確實包含『資料來源1』與『作業』這幾個字。")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
🔍 正在幫你搜尋檔案，請稍候...
✅ 找到了！路徑是：/content/drive/MyDrive/Colab Notebooks/金融資料探勘/資料來源1(作業).csv
------------------------------
🎉 處理成功！新檔案已儲存：
/content/drive/MyDrive/Colab Notebooks/金融資料探勘/資料來源1_含file欄位_作業版.csv

        年月日     收盤價(元)                    file (作業)
0  2021/1/4  14,902.03  OptionsDaily_2021_01_04.csv
1  2021/1/5  15,000.03  OptionsDaily_2021_01_05.csv
2  2021/1/6  14,983.13  OptionsDaily_2021_01_06.csv
3  2021/1/7     15,214  OptionsDaily_2021_01_07.csv
4  2021/1/8  15,463.95  OptionsDaily_2021_01_08.csv

In [6]:
import pandas as pd
from google.colab import drive
import os

# 1. 掛載 Google Drive
drive.mount('/content/drive')

# 2. 設定要搜尋的檔案名稱
trading_file_name = "資料來源1_含file欄位_作業版.csv"  # 剛才產生的檔案
expiry_file_name = "資料來源3(作業).csv"              # 到期日原始檔

print("🔍 正在搜尋相關檔案...")

trading_path = None
expiry_path = None

# 自動搜尋檔案路徑
for root, dirs, files in os.walk('/content/drive/MyDrive/'):
    if trading_file_name in files:
        trading_path = os.path.join(root, trading_file_name)
    if expiry_file_name in files:
        expiry_path = os.path.join(root, expiry_file_name)
    # 如果全形括號的話也找一下
    elif "資料來源3（作業）.csv" in files:
        expiry_path = os.path.join(root, "資料來源3（作業）.csv")

# 3. 執行資料處理
if trading_path and expiry_path:
    print(f"✅ 找到交易檔：{trading_path}")
    print(f"✅ 找到到期日檔：{expiry_path}")

    # 讀取資料 (到期日檔無標題，需手動給欄位名)
    df_trading = pd.read_csv(trading_path)
    df_expiry = pd.read_csv(expiry_path, header=None)
    df_expiry.columns = ['最後結算日', '契約月份', '結算價']

    # A. 轉換日期格式
    df_trading['年月日_dt'] = pd.to_datetime(df_trading['年月日'])
    df_expiry['最後結算日_dt'] = pd.to_datetime(df_expiry['最後結算日'])

    # B. 篩選月選擇權 (排除名稱含 'W' 的週契約)
    df_monthly = df_expiry[~df_expiry['契約月份'].astype(str).str.contains('W')].copy()
    df_monthly = df_monthly.sort_values('最後結算日_dt')

    # C. 定義邏輯：尋找最近一個月合約且 Maturity >= 1
    def get_contract_info(trade_date):
        # 條件：最後結算日 - 交易日 >= 1
        valid = df_monthly[df_monthly['最後結算日_dt'] >= (trade_date + pd.Timedelta(days=1))]
        if not valid.empty:
            nearest = valid.iloc[0]
            contract = nearest['契約月份']
            expiry = nearest['最後結算日_dt']
            maturity = (expiry - trade_date).days
            return pd.Series([contract, expiry.strftime('%Y/%m/%d'), maturity])
        return pd.Series([None, None, None])

    # 執行比對
    print("⏳ 正在計算契約與到期天數...")
    df_trading[['Contract', 'ContractExpiryDate', 'Maturity']] = df_trading['年月日_dt'].apply(get_contract_info)

    # 4. 儲存結果
    output_path = os.path.join(os.path.dirname(trading_path), '資料來源1_含Contract資訊_作業版.csv')
    # 刪除暫存的日期欄位後存檔
    df_final = df_trading.drop(columns=['年月日_dt'])
    df_final.to_csv(output_path, index=False, encoding='utf-8-sig')

    print("-" * 30)
    print(f"🎉 處理成功！新檔案已儲存：\n{output_path}")
    display(df_final.head(10))
else:
    print("❌ 搜尋失敗，請確認這兩個檔案都在雲端硬碟中：")
    print(f"1. {trading_file_name}")
    print(f"2. {expiry_file_name}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
🔍 正在搜尋相關檔案...
✅ 找到交易檔：/content/drive/MyDrive/Colab Notebooks/金融資料探勘/資料來源1_含file欄位_作業版.csv
✅ 找到到期日檔：/content/drive/MyDrive/Colab Notebooks/金融資料探勘/資料來源3(作業).csv
⏳ 正在計算契約與到期天數...
------------------------------
🎉 處理成功！新檔案已儲存：
/content/drive/MyDrive/Colab Notebooks/金融資料探勘/資料來源1_含Contract資訊_作業版.csv

,年月日,收盤價(元),file (作業),Contract,ContractExpiryDate,Maturity
0,2021/1/4,"14,902.03",OptionsDaily_2021_01_04.csv,202101,2021/01/20,16
1,2021/1/5,"15,000.03",OptionsDaily_2021_01_05.csv,202101,2021/01/20,15
2,2021/1/6,"14,983.13",OptionsDaily_2021_01_06.csv,202101,2021/01/20,14
3,2021/1/7,"15,214",OptionsDaily_2021_01_07.csv,202101,2021/01/20,13
4,2021/1/8,"15,463.95",OptionsDaily_2021_01_08.csv,202101,2021/01/20,12
5,2021/1/11,"15,557.30",OptionsDaily_2021_01_11.csv,202101,2021/01/20,9
6,2021/1/12,"15,500.70",OptionsDaily_2021_01_12.csv,202101,2021/01/20,8
7,2021/1/13,"15,769.98",OptionsDaily_2021_01_13.csv,202101,2021/01/20,7
8,2021/1/14,"15,707.19",OptionsDaily_2021_01_14.csv,202101,2021/01/20,6
9,2021/1/15,"15,616.39",OptionsDaily_2021_01_15.csv,202101,2021/01/20,5

In [7]:
import pandas as pd
from google.colab import drive
import os

# 1. 掛載 Google Drive
drive.mount('/content/drive')

# 2. 設定要搜尋的輸入檔案 (上一步產生的結果)
input_file_name = "資料來源1_含Contract資訊_作業版.csv"

print("🔍 正在搜尋交易資料檔...")

input_path = None
# 自動搜尋檔案路徑
for root, dirs, files in os.walk('/content/drive/MyDrive/'):
    if input_file_name in files:
        input_path = os.path.join(root, input_file_name)
        break

# 3. 執行利率處理
if input_path:
    print(f"✅ 找到檔案：{input_path}")

    # 讀取資料
    df = pd.read_csv(input_path)

    # 4. 新增 Rf 欄位
    # 根據 2021 年台灣銀行一年期定期儲蓄存款「機動利率」
    # 該年度利率維持在 0.84%
    print("⏳ 正在填入 2021 年無風險利率 (Rf = 0.84)...")
    df['Rf'] = 0.84

    # 5. 儲存最終作業檔案
    output_path = os.path.join(os.path.dirname(input_path), '資料來源1_含Rf_作業最終版.csv')
    df.to_csv(output_path, index=False, encoding='utf-8-sig')

    print("-" * 30)
    print(f"🎉 利率處理完成！最終檔案已儲存：\n{output_path}")

    # 顯示前 10 筆確認結果
    display(df.head(10))
else:
    print(f"❌ 找不到檔案：{input_file_name}")
    print("請確認上一步的『含Contract資訊』檔案已經成功產生在雲端硬碟中。")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
🔍 正在搜尋交易資料檔...
✅ 找到檔案：/content/drive/MyDrive/Colab Notebooks/金融資料探勘/資料來源1_含Contract資訊_作業版.csv
⏳ 正在填入 2021 年無風險利率 (Rf = 0.84)...
------------------------------
🎉 利率處理完成！最終檔案已儲存：
/content/drive/MyDrive/Colab Notebooks/金融資料探勘/資料來源1_含Rf_作業最終版.csv

,年月日,收盤價(元),file (作業),Contract,ContractExpiryDate,Maturity,Rf
0,2021/1/4,"14,902.03",OptionsDaily_2021_01_04.csv,202101,2021/01/20,16,0.84
1,2021/1/5,"15,000.03",OptionsDaily_2021_01_05.csv,202101,2021/01/20,15,0.84
2,2021/1/6,"14,983.13",OptionsDaily_2021_01_06.csv,202101,2021/01/20,14,0.84
3,2021/1/7,"15,214",OptionsDaily_2021_01_07.csv,202101,2021/01/20,13,0.84
4,2021/1/8,"15,463.95",OptionsDaily_2021_01_08.csv,202101,2021/01/20,12,0.84
5,2021/1/11,"15,557.30",OptionsDaily_2021_01_11.csv,202101,2021/01/20,9,0.84
6,2021/1/12,"15,500.70",OptionsDaily_2021_01_12.csv,202101,2021/01/20,8,0.84
7,2021/1/13,"15,769.98",OptionsDaily_2021_01_13.csv,202101,2021/01/20,7,0.84
8,2021/1/14,"15,707.19",OptionsDaily_2021_01_14.csv,202101,2021/01/20,6,0.84
9,2021/1/15,"15,616.39",OptionsDaily_2021_01_15.csv,202101,2021/01/20,5,0.84