# Textual Data Analysis Pipeline Dashboard

In [2]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import os
import sys
from pathlib import Path
from datetime import datetime

# Set project root so notebooks can import src and utils.
PROJECT_ROOT = Path.cwd().resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.get_data import JudicialLoader, generate_date_range
from utils.pipeline_preprocess import run_preprocessing
from utils.pipeline_features import build_features
from utils.pipeline_modeling import (
    load_modeling_data,
    check_mnir_runtime,
    load_jtype_verdict_summary,
    stratified_sample_modeling_data,
    split_modeling_data,
    apply_chi2_feature_selection,
    run_mnir_feature_extraction,
    tune_chi2_k_with_validation,
    run_step3_batch,
    run_direct_svm_batch,
    patch_step3_direct_svm_batch,
    save_step3_artifacts,
    build_model_comparison,
    evaluate_svm_grid,
    evaluate_majority_baseline,
    evaluate_all_models,
)

### Getting Data

In [ ]:
# url 已死
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36",
    "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Im93bm1lOTUxNzIiLCJleHAiOjE3NDE0MTM5Mjl9.wXE3tcXoMrbyPXRG90K001HN3Fm8QCLhhB8YwFhlBz8"
}

url_range = range(53746, 54094)
year_months = generate_date_range(1996, 1, 2024, 12)

loader = JudicialLoader(headers=headers)

loader.run_all(url_range=url_range, year_months=year_months)

### Step 1: Data Preprocessing (資料前處理)
從 `parquet_folder` 指定的資料夾讀取 `raw_extracted.parquet` 與 `full_text_backup.parquet`，計算 JTYPE/VERDICT，並萃取事實文字。

> **第一次執行前**：請將 `PARQUET_FOLDER` 設為含有下列兩個檔案的資料夾路徑：
> - `raw_extracted.parquet`（含 65 欄位元資料）
> - `full_text_backup.parquet`（含 JID + JFULL）

> **cache 說明**：
> - 第一次執行後，`artifacts/cache/` 會自動建立快取（儲存 JTYPE 與 main_clause，**不含** VERDICT）。
> - **若只是修改 `config/patterns.py` 重新標注 VERDICT**：將 `PARQUET_FOLDER` 設為 `None`，即可從快取快速重算（毋需刪除快取，幾秒內完成）。
> - **若需重新計算 JTYPE**（修改了 `j_type_check` 邏輯）：仍需設回 parquet 路徑。

**output**
1. **實體檔案**：
   - `artifacts/reports/judgment_labels.xlsx`: 有效案件的 JTYPE + VERDICT 標籤（過濾掉 RULING / 不重要）。
   - `artifacts/reports/raw_extracted.xlsx`: 全部案件的完整欄位（不含 JFULL）。
   - `artifacts/reports/fact_removed_blank.xlsx`: 乾淨的「犯罪事實 / 事實及理由」文字，供 Step 2 斷詞使用。
   - `artifacts/cache/raw_extracted.parquet`: 輕量化核心特徵緩存（下次執行直接讀取）。
2. **記憶體回傳值 (`df_clean`)**：含所有案件欄位的 DataFrame（JTYPE、VERDICT 等），不含 JFULL。

In [ ]:
# First run from parquet input: set PARQUET_FOLDER to "../data/raw_parquet".
# Fast relabel/rebuild from pipeline cache: keep PARQUET_FOLDER = None.
# PARQUET_FOLDER = "../data/raw_parquet"
PARQUET_FOLDER = None

df_clean = run_preprocessing(
    parquet_folder=PARQUET_FOLDER,
    output_folder="../data/processed/IP_Law_cases",
    artifacts_folder="../artifacts/reports",
    n_jobs=-1  # n_jobs=1 for sequential; n_jobs=-1 uses available CPU workers
)

# display(df_clean)

### Step 2: Tokenization & DTM (斷詞與特徵矩陣)
使用 CKIP 建立斷詞，並計算 Bag-of-Words (BoW) 與 TF-IDF 矩陣。

**output**
1. **實體檔案 (非常耗時，通常只需跑一次)**：
   - `artifacts/reports/word_seg.xlsx`: 儲存經過 CkipWordSegmenter 斷詞後的每個字串陣列。
   - `artifacts/reports/verdict_results.xlsx`: 對齊過斷詞順序的最終 One-Hot 標籤集。
   - `artifacts/features/dtm/dtm_csr_BoW.npz`: Bag of Words 的 Sparse 特徵稀疏矩陣。
   - `artifacts/features/dtm/dtm_csr_TF_IDF.npz`: TF-IDF 的 Sparse 特徵稀疏矩陣。
2. **記憶體回傳值變數 (`dtm_features`)**：回傳建立好的特徵矩陣以供查看維度。

In [ ]:
TARGET_VERDICTS = ["Win", "Lose", "Mixed"]

JTYPE_DATASETS = {
    "administrative_win_lose_mixed": ["ADMINISTRATIVE"],
    "civil_win_lose_mixed": ["CIVIL"],
    "criminal_win_lose_mixed": ["CRIMINAL"],
    "cwc_win_lose_mixed": ["CWC"],
}

for dataset_name, target_jtypes in JTYPE_DATASETS.items():
    for remove_leakage in [False, True]:

        build_features(
            df_clean_path="../artifacts/reports/fact_removed_blank.xlsx",
            artifacts_folder="../artifacts/reports",
            lexicon_folder="../resources/lexicons",
            dictionary_folder="../resources/dictionaries",
            features_folder="../artifacts/features/dtm",
            target_jtypes=target_jtypes,
            target_verdicts=TARGET_VERDICTS,
            dataset_name=dataset_name,
            remove_leakage=remove_leakage,
            force_recompute_seg=False,
            verbose=False,
            show_progress=True
        )

### Step 3: Batch Modeling & Evaluation
Run MNIR + SVM experiments across case types, leakage variants, and DTM representations.

This step is the full experiment and can take a long time. If you only need to fix the Direct SVM baseline K-selection issue in an existing run, use Step 4 instead.

In [4]:
# Step 3.1 Batch controls
# RUN_MODE="quick" is for smoke tests. RUN_MODE="full" is for final results.
RUN_MODE = "full"

FEATURES_FOLDER = "../artifacts/features/dtm"
ARTIFACTS_FOLDER = "../artifacts/reports"
MNIR_FEATURES_FOLDER = "../artifacts/features/mnir"

DATASET_NAMES = [
    "administrative_win_lose_mixed",
    "civil_win_lose_mixed",
    "criminal_win_lose_mixed",
    "cwc_win_lose_mixed",
]
REMOVE_LEAKAGE_VALUES = [False, True]
REPRESENTATIONS = ["bow", "tf", "tfidf"]

RANDOM_STATE = 42
TRAIN_SIZE = 0.70
VAL_SIZE = 0.10
TEST_SIZE = 0.20

if RUN_MODE == "quick":
    MAX_ROWS = 1200
    CHI2_K_GRID = [500, 1000]
    SVM_C_GRID = [0.25, 1.0]
elif RUN_MODE == "full":
    MAX_ROWS = None
    CHI2_K_GRID = [1000, 3000, 5000, 10000]
    SVM_C_GRID = [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]
else:
    raise ValueError("RUN_MODE must be 'quick' or 'full'.")

RUN_TAG = f"{RUN_MODE}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
mnir_runtime = check_mnir_runtime(require_textir=True)
print("RUN_MODE:", RUN_MODE)
print("DATASET_NAMES:", DATASET_NAMES)
print("REMOVE_LEAKAGE_VALUES:", REMOVE_LEAKAGE_VALUES)
print("REPRESENTATIONS:", REPRESENTATIONS)
print("MAX_ROWS:", MAX_ROWS)
print("CHI2_K_GRID:", CHI2_K_GRID)
print("SVM_C_GRID:", SVM_C_GRID)
print("RUN_TAG:", RUN_TAG)
print("MNIR runtime ready:", mnir_runtime["ok"])
display(pd.DataFrame([mnir_runtime]))
if not mnir_runtime["ok"]:
    raise RuntimeError("MNIR runtime is not ready. Check the diagnostic table above.")

RUN_MODE: full
DATASET_NAMES: ['administrative_win_lose_mixed', 'civil_win_lose_mixed', 'criminal_win_lose_mixed', 'cwc_win_lose_mixed']
REMOVE_LEAKAGE_VALUES: [False, True]
REPRESENTATIONS: ['bow', 'tf', 'tfidf']
MAX_ROWS: None
CHI2_K_GRID: [1000, 3000, 5000, 10000]
SVM_C_GRID: [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]
RUN_TAG: full_20260504_154912
MNIR runtime ready: True

,python_executable,R_HOME,R_on_path,Rscript_on_path,R_version,Matrix,textir,error,ok
0,c:\Users\User\anaconda3\envs\tm\python.exe,None,C:\Users\User\anaconda3\envs\tm\Scripts\R.EXE,C:\Users\User\anaconda3\envs\tm\Scripts\Rscrip...,R version 3.6.3 (2020-02-29),ok,ok,None,True

In [5]:
# Step 3.2 Run batch experiments
batch_results = run_step3_batch(
    dataset_names=DATASET_NAMES,
    remove_leakage_values=REMOVE_LEAKAGE_VALUES,
    representations=REPRESENTATIONS,
    run_mode=RUN_MODE,
    run_tag=RUN_TAG,
    max_rows=MAX_ROWS,
    chi2_k_grid=CHI2_K_GRID,
    svm_c_grid=SVM_C_GRID,
    train_size=TRAIN_SIZE,
    val_size=VAL_SIZE,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    features_folder=FEATURES_FOLDER,
    artifacts_folder=ARTIFACTS_FOLDER,
    mnir_features_folder=MNIR_FEATURES_FOLDER,
)

step3_batch_summary = batch_results["summary_df"]
step3_batch_failures = batch_results["failures_df"]

BATCH_ARTIFACT_DIR = os.path.join(ARTIFACTS_FOLDER, "step3_batch_runs", RUN_TAG)
os.makedirs(BATCH_ARTIFACT_DIR, exist_ok=True)
summary_path = os.path.join(BATCH_ARTIFACT_DIR, "batch_summary.csv")
failures_path = os.path.join(BATCH_ARTIFACT_DIR, "batch_failures.csv")
step3_batch_summary.to_csv(summary_path, index=False, encoding="utf-8-sig")
step3_batch_failures.to_csv(failures_path, index=False, encoding="utf-8-sig")

print("Batch summary saved to:", summary_path)
print("Batch failures saved to:", failures_path)
display(step3_batch_summary)
if not step3_batch_failures.empty:
    display(step3_batch_failures)

[Step3] administrative_win_lose_mixed / with_leakage / bow
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\bow_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\bow_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\bow_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\bow_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\bow_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\bow_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\bow_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\bow_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\bow_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\bow_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\bow_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\bow_chi2_k10000\mnir_z_test.npy

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Step3] administrative_win_lose_mixed / with_leakage / tf
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tf_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tf_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tf_chi2_k10000\mnir_z_test.npy
[Step3] administrative_win_lose_mixed / with_leakage / tfidf
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tfidf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tfidf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tfidf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tfidf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tfidf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tfidf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tfidf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tfidf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tfidf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tfidf_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tfidf_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\with_leakage\tfidf_chi2_k10000\mnir_z_test.npy
[Step3] administrative_win_lose_mixed / no_leakage / bow
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\bow_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\bow_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\bow_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\bow_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\bow_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\bow_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\bow_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\bow_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\bow_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\bow_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\bow_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\bow_chi2_k10000\mnir_z_test.npy

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Step3] administrative_win_lose_mixed / no_leakage / tf
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tf_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tf_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tf_chi2_k10000\mnir_z_test.npy
[Step3] administrative_win_lose_mixed / no_leakage / tfidf
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tfidf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tfidf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tfidf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tfidf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tfidf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tfidf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tfidf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tfidf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tfidf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tfidf_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tfidf_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\administrative_win_lose_mixed\no_leakage\tfidf_chi2_k10000\mnir_z_test.npy
[Step3] civil_win_lose_mixed / with_leakage / bow
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\bow_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\bow_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\bow_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\bow_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\bow_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\bow_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\bow_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\bow_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\bow_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\bow_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\bow_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\bow_chi2_k10000\mnir_z_test.npy

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Step3] civil_win_lose_mixed / with_leakage / tf
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tf_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tf_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tf_chi2_k10000\mnir_z_test.npy
[Step3] civil_win_lose_mixed / with_leakage / tfidf
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tfidf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tfidf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tfidf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tfidf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tfidf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tfidf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tfidf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tfidf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tfidf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tfidf_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tfidf_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\with_leakage\tfidf_chi2_k10000\mnir_z_test.npy
[Step3] civil_win_lose_mixed / no_leakage / bow
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\bow_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\bow_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\bow_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\bow_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\bow_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\bow_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\bow_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\bow_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\bow_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\bow_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\bow_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\bow_chi2_k10000\mnir_z_test.npy

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Step3] civil_win_lose_mixed / no_leakage / tf
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tf_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tf_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tf_chi2_k10000\mnir_z_test.npy
[Step3] civil_win_lose_mixed / no_leakage / tfidf
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tfidf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tfidf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tfidf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tfidf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tfidf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tfidf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tfidf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tfidf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tfidf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tfidf_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tfidf_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\civil_win_lose_mixed\no_leakage\tfidf_chi2_k10000\mnir_z_test.npy
[Step3] criminal_win_lose_mixed / with_leakage / bow
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\bow_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\bow_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\bow_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\bow_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\bow_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\bow_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\bow_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\bow_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\bow_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\bow_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\bow_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\bow_chi2_k10000\mnir_z_test.npy

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Step3] criminal_win_lose_mixed / with_leakage / tf
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tf_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tf_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tf_chi2_k10000\mnir_z_test.npy
[Step3] criminal_win_lose_mixed / with_leakage / tfidf
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tfidf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tfidf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tfidf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tfidf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tfidf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tfidf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tfidf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tfidf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tfidf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tfidf_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tfidf_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\with_leakage\tfidf_chi2_k10000\mnir_z_test.npy
[Step3] criminal_win_lose_mixed / no_leakage / bow
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\bow_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\bow_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\bow_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\bow_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\bow_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\bow_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\bow_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\bow_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\bow_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\bow_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\bow_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\bow_chi2_k10000\mnir_z_test.npy
[Step3] criminal_win_lose_mixed / no_leakage / tf
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tf_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tf_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tf_chi2_k10000\mnir_z_test.npy
[Step3] criminal_win_lose_mixed / no_leakage / tfidf
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tfidf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tfidf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tfidf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tfidf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tfidf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tfidf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tfidf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tfidf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tfidf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tfidf_chi2_k10000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tfidf_chi2_k10000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\criminal_win_lose_mixed\no_leakage\tfidf_chi2_k10000\mnir_z_test.npy
[Step3] cwc_win_lose_mixed / with_leakage / bow
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\bow_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\bow_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\bow_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\bow_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\bow_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\bow_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\bow_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\bow_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\bow_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\bow_chi2_k5912\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\bow_chi2_k5912\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\bow_chi2_k5912\mnir_z_test.npy

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Step3] cwc_win_lose_mixed / with_leakage / tf
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tf_chi2_k5912\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tf_chi2_k5912\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tf_chi2_k5912\mnir_z_test.npy
[Step3] cwc_win_lose_mixed / with_leakage / tfidf
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tfidf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tfidf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tfidf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tfidf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tfidf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tfidf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tfidf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tfidf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tfidf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tfidf_chi2_k5912\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tfidf_chi2_k5912\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\with_leakage\tfidf_chi2_k5912\mnir_z_test.npy
[Step3] cwc_win_lose_mixed / no_leakage / bow
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\bow_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\bow_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\bow_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\bow_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\bow_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\bow_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\bow_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\bow_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\bow_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\bow_chi2_k5773\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\bow_chi2_k5773\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\bow_chi2_k5773\mnir_z_test.npy

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Step3] cwc_win_lose_mixed / no_leakage / tf
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tf_chi2_k5773\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tf_chi2_k5773\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tf_chi2_k5773\mnir_z_test.npy
[Step3] cwc_win_lose_mixed / no_leakage / tfidf
[MNIR] cached feature shape does not match current split; recomputing MNIR features.
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tfidf_chi2_k1000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tfidf_chi2_k1000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tfidf_chi2_k1000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tfidf_chi2_k3000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tfidf_chi2_k3000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tfidf_chi2_k3000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tfidf_chi2_k5000\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tfidf_chi2_k5000\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tfidf_chi2_k5000\mnir_z_test.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tfidf_chi2_k5773\mnir_z_train.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tfidf_chi2_k5773\mnir_z_val.npy
[MNIR] saved: ..\artifacts\features\mnir\cwc_win_lose_mixed\no_leakage\tfidf_chi2_k5773\mnir_z_test.npy
Batch summary saved to: ../artifacts/reports\step3_batch_runs\full_20260504_154912\batch_summary.csv
Batch failures saved to: ../artifacts/reports\step3_batch_runs\full_20260504_154912\batch_failures.csv

,run_mode,run_tag,dataset_name,dataset_slug,remove_leakage,leakage_variant,representation,dtm_path,max_rows,train_size,...,test_size,random_state,chi2_k_grid,svm_c_grid,best_chi2_k,best_svm_c,baseline_models,output_dir,Test Accuracy,Test Macro F1
0,full,full_20260504_154912,administrative_win_lose_mixed,administrative_win_lose_mixed,False,with_leakage,bow,../artifacts/features/dtm\administrative_win_l...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",3000,0.0625,"[Majority Class, BOW + SVM]",../artifacts/reports\administrative_win_lose_m...,0.875387,0.314817
1,full,full_20260504_154912,administrative_win_lose_mixed,administrative_win_lose_mixed,False,with_leakage,tf,../artifacts/features/dtm\administrative_win_l...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",1000,0.0625,"[Majority Class, TF + SVM]",../artifacts/reports\administrative_win_lose_m...,0.876270,0.311352
2,full,full_20260504_154912,administrative_win_lose_mixed,administrative_win_lose_mixed,False,with_leakage,tfidf,../artifacts/features/dtm\administrative_win_l...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",10000,1.0000,"[Majority Class, TFIDF + SVM]",../artifacts/reports\administrative_win_lose_m...,0.873177,0.310912
3,full,full_20260504_154912,administrative_win_lose_mixed,administrative_win_lose_mixed,True,no_leakage,bow,../artifacts/features/dtm\administrative_win_l...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",5000,0.0625,"[Majority Class, BOW + SVM]",../artifacts/reports\administrative_win_lose_m...,0.875387,0.318371
4,full,full_20260504_154912,administrative_win_lose_mixed,administrative_win_lose_mixed,True,no_leakage,tf,../artifacts/features/dtm\administrative_win_l...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",1000,0.0625,"[Majority Class, TF + SVM]",../artifacts/reports\administrative_win_lose_m...,0.876270,0.311352
5,full,full_20260504_154912,administrative_win_lose_mixed,administrative_win_lose_mixed,True,no_leakage,tfidf,../artifacts/features/dtm\administrative_win_l...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",5000,2.0000,"[Majority Class, TFIDF + SVM]",../artifacts/reports\administrative_win_lose_m...,0.873619,0.310922
6,full,full_20260504_154912,civil_win_lose_mixed,civil_win_lose_mixed,False,with_leakage,bow,../artifacts/features/dtm\civil_win_lose_mixed...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",10000,0.0625,"[Majority Class, BOW + SVM]",../artifacts/reports\civil_win_lose_mixed\with...,0.681377,0.338749
7,full,full_20260504_154912,civil_win_lose_mixed,civil_win_lose_mixed,False,with_leakage,tf,../artifacts/features/dtm\civil_win_lose_mixed...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",3000,4.0000,"[Majority Class, TF + SVM]",../artifacts/reports\civil_win_lose_mixed\with...,0.692851,0.336974
8,full,full_20260504_154912,civil_win_lose_mixed,civil_win_lose_mixed,False,with_leakage,tfidf,../artifacts/features/dtm\civil_win_lose_mixed...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",3000,0.5000,"[Majority Class, TFIDF + SVM]",../artifacts/reports\civil_win_lose_mixed\with...,0.694616,0.364384
9,full,full_20260504_154912,civil_win_lose_mixed,civil_win_lose_mixed,True,no_leakage,bow,../artifacts/features/dtm\civil_win_lose_mixed...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",10000,0.5000,"[Majority Class, BOW + SVM]",../artifacts/reports\civil_win_lose_mixed\no_l...,0.677846,0.335769
10,full,full_20260504_154912,civil_win_lose_mixed,civil_win_lose_mixed,True,no_leakage,tf,../artifacts/features/dtm\civil_win_lose_mixed...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",1000,0.2500,"[Majority Class, TF + SVM]",../artifacts/reports\civil_win_lose_mixed\no_l...,0.686673,0.320197
11,full,full_20260504_154912,civil_win_lose_mixed,civil_win_lose_mixed,True,no_leakage,tfidf,../artifacts/features/dtm\civil_win_lose_mixed...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",1000,0.1250,"[Majority Class, TFIDF + SVM]",../artifacts/reports\civil_win_lose_mixed\no_l...,0.695499,0.352523
12,full,full_20260504_154912,criminal_win_lose_mixed,criminal_win_lose_mixed,False,with_leakage,bow,../artifacts/features/dtm\criminal_win_lose_mi...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",10000,0.0625,"[Majority Class, BOW + SVM]",../artifacts/reports\criminal_win_lose_mixed\w...,0.924431,0.360331
13,full,full_20260504_154912,criminal_win_lose_mixed,criminal_win_lose_mixed,False,with_leakage,tf,../artifacts/features/dtm\criminal_win_lose_mi...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",5000,0.5000,"[Majority Class, TF + SVM]",../artifacts/reports\criminal_win_lose_mixed\w...,0.933423,0.366935
14,full,full_20260504_154912,criminal_win_lose_mixed,criminal_win_lose_mixed,False,with_leakage,tfidf,../artifacts/features/dtm\criminal_win_lose_mi...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",3000,0.2500,"[Majority Class, TFIDF + SVM]",../artifacts/reports\criminal_win_lose_mixed\w...,0.925579,0.382485
15,full,full_20260504_154912,criminal_win_lose_mixed,criminal_win_lose_mixed,True,no_leakage,bow,../artifacts/features/dtm\criminal_win_lose_mi...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",10000,0.1250,"[Majority Class, BOW + SVM]",../artifacts/reports\criminal_win_lose_mixed\n...,0.925196,0.363551
16,full,full_20260504_154912,criminal_win_lose_mixed,criminal_win_lose_mixed,True,no_leakage,tf,../artifacts/features/dtm\criminal_win_lose_mi...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",1000,0.0625,"[Majority Class, TF + SVM]",../artifacts/reports\criminal_win_lose_mixed\n...,0.933805,0.370219
17,full,full_20260504_154912,criminal_win_lose_mixed,criminal_win_lose_mixed,True,no_leakage,tfidf,../artifacts/features/dtm\criminal_win_lose_mi...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",5000,0.1250,"[Majority Class, TFIDF + SVM]",../artifacts/reports\criminal_win_lose_mixed\n...,0.927683,0.390219
18,full,full_20260504_154912,cwc_win_lose_mixed,cwc_win_lose_mixed,False,with_leakage,bow,../artifacts/features/dtm\cwc_win_lose_mixed\w...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",3000,0.0625,"[Majority Class, BOW + SVM]",../artifacts/reports\cwc_win_lose_mixed\with_l...,0.853591,0.570599
19,full,full_20260504_154912,cwc_win_lose_mixed,cwc_win_lose_mixed,False,with_leakage,tf,../artifacts/features/dtm\cwc_win_lose_mixed\w...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",1000,0.0625,"[Majority Class, TF + SVM]",../artifacts/reports\cwc_win_lose_mixed\with_l...,0.842541,0.560802
20,full,full_20260504_154912,cwc_win_lose_mixed,cwc_win_lose_mixed,False,with_leakage,tfidf,../artifacts/features/dtm\cwc_win_lose_mixed\w...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",3000,0.0625,"[Majority Class, TFIDF + SVM]",../artifacts/reports\cwc_win_lose_mixed\with_l...,0.845304,0.562346
21,full,full_20260504_154912,cwc_win_lose_mixed,cwc_win_lose_mixed,True,no_leakage,bow,../artifacts/features/dtm\cwc_win_lose_mixed\n...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",3000,0.0625,"[Majority Class, BOW + SVM]",../artifacts/reports\cwc_win_lose_mixed\no_lea...,0.814917,0.542014
22,full,full_20260504_154912,cwc_win_lose_mixed,cwc_win_lose_mixed,True,no_leakage,tf,../artifacts/features/dtm\cwc_win_lose_mixed\n...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",1000,0.1250,"[Majority Class, TF + SVM]",../artifacts/reports\cwc_win_lose_mixed\no_lea...,0.823204,0.545364
23,full,full_20260504_154912,cwc_win_lose_mixed,cwc_win_lose_mixed,True,no_leakage,tfidf,../artifacts/features/dtm\cwc_win_lose_mixed\n...,None,0.7,...,0.2,42,"[1000, 3000, 5000, 10000]","[0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]",3000,0.1250,"[Majority Class, TFIDF + SVM]",../artifacts/reports\cwc_win_lose_mixed\no_lea...,0.812155,0.537288

### Step 4: Patch Direct SVM Baseline Only
This step does not rerun MNIR. It only recomputes the Direct SVM baseline with its own chi-square K tuning and patches the existing Step 3 run folders.

It updates files such as `model_comparison.csv`, `baseline_*`, `direct_svm_chi2_*`, and `run_config.csv` inside the original `step3_runs/{PATCH_RUN_TAG}` folders.

In [7]:
# Step 4.1 Patch controls
PATCH_RUN_MODE = "full"
PATCH_RUN_TAG = "full_20260504_154912"
PATCH_MAX_ROWS = None
PATCH_CHI2_K_GRID = [1000, 3000, 5000, 10000]
PATCH_SVM_C_GRID = [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]

print("PATCH_RUN_MODE:", PATCH_RUN_MODE)
print("PATCH_RUN_TAG:", PATCH_RUN_TAG)
print("PATCH_MAX_ROWS:", PATCH_MAX_ROWS)
print("PATCH_CHI2_K_GRID:", PATCH_CHI2_K_GRID)
print("PATCH_SVM_C_GRID:", PATCH_SVM_C_GRID)

PATCH_RUN_MODE: full
PATCH_RUN_TAG: full_20260504_154912
PATCH_MAX_ROWS: None
PATCH_CHI2_K_GRID: [1000, 3000, 5000, 10000]
PATCH_SVM_C_GRID: [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0, 4.0]

In [8]:
# Step 4.2 Recompute Direct SVM only and patch existing Step 3 outputs
patch_results = patch_step3_direct_svm_batch(
    dataset_names=DATASET_NAMES,
    remove_leakage_values=REMOVE_LEAKAGE_VALUES,
    representations=REPRESENTATIONS,
    run_mode=PATCH_RUN_MODE,
    run_tag=PATCH_RUN_TAG,
    max_rows=PATCH_MAX_ROWS,
    chi2_k_grid=PATCH_CHI2_K_GRID,
    svm_c_grid=PATCH_SVM_C_GRID,
    train_size=TRAIN_SIZE,
    val_size=VAL_SIZE,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    features_folder=FEATURES_FOLDER,
    artifacts_folder=ARTIFACTS_FOLDER,
)

patch_summary = patch_results["summary_df"]
patch_failures = patch_results["failures_df"]

PATCH_ARTIFACT_DIR = os.path.join(ARTIFACTS_FOLDER, "step4_direct_svm_patch_runs", PATCH_RUN_TAG)
os.makedirs(PATCH_ARTIFACT_DIR, exist_ok=True)
patch_summary_path = os.path.join(PATCH_ARTIFACT_DIR, "direct_svm_patch_summary.csv")
patch_failures_path = os.path.join(PATCH_ARTIFACT_DIR, "direct_svm_patch_failures.csv")
patch_summary.to_csv(patch_summary_path, index=False, encoding="utf-8-sig")
patch_failures.to_csv(patch_failures_path, index=False, encoding="utf-8-sig")

print("Patch summary saved to:", patch_summary_path)
print("Patch failures saved to:", patch_failures_path)
print("Patched runs:", len(patch_summary))
print("Failures:", len(patch_failures))
display(patch_summary)
if not patch_failures.empty:
    display(patch_failures)

[Patch Direct SVM] administrative_win_lose_mixed / with_leakage / bow

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Patch Direct SVM] administrative_win_lose_mixed / with_leakage / tf
[Patch Direct SVM] administrative_win_lose_mixed / with_leakage / tfidf
[Patch Direct SVM] administrative_win_lose_mixed / no_leakage / bow

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Patch Direct SVM] administrative_win_lose_mixed / no_leakage / tf
[Patch Direct SVM] administrative_win_lose_mixed / no_leakage / tfidf
[Patch Direct SVM] civil_win_lose_mixed / with_leakage / bow

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Patch Direct SVM] civil_win_lose_mixed / with_leakage / tf
[Patch Direct SVM] civil_win_lose_mixed / with_leakage / tfidf
[Patch Direct SVM] civil_win_lose_mixed / no_leakage / bow

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Patch Direct SVM] civil_win_lose_mixed / no_leakage / tf
[Patch Direct SVM] civil_win_lose_mixed / no_leakage / tfidf
[Patch Direct SVM] criminal_win_lose_mixed / with_leakage / bow

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Patch Direct SVM] criminal_win_lose_mixed / with_leakage / tf
[Patch Direct SVM] criminal_win_lose_mixed / with_leakage / tfidf
[Patch Direct SVM] criminal_win_lose_mixed / no_leakage / bow

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Patch Direct SVM] criminal_win_lose_mixed / no_leakage / tf
[Patch Direct SVM] criminal_win_lose_mixed / no_leakage / tfidf
[Patch Direct SVM] cwc_win_lose_mixed / with_leakage / bow

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Patch Direct SVM] cwc_win_lose_mixed / with_leakage / tf
[Patch Direct SVM] cwc_win_lose_mixed / with_leakage / tfidf
[Patch Direct SVM] cwc_win_lose_mixed / no_leakage / bow

c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\User\anaconda3\envs\tm\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

[Patch Direct SVM] cwc_win_lose_mixed / no_leakage / tf
[Patch Direct SVM] cwc_win_lose_mixed / no_leakage / tfidf
Patch summary saved to: ../artifacts/reports\step4_direct_svm_patch_runs\full_20260504_154912\direct_svm_patch_summary.csv
Patch failures saved to: ../artifacts/reports\step4_direct_svm_patch_runs\full_20260504_154912\direct_svm_patch_failures.csv
Patched runs: 24
Failures: 0

,Unnamed: 0,run_mode,run_tag,dataset_name,dataset_slug,remove_leakage,leakage_variant,representation,dtm_path,max_rows,...,baseline_models,direct_svm_tuning,best_direct_chi2_k,best_direct_svm_c,direct_svm_patch_run_mode,direct_svm_patch_run_tag,direct_svm_patch_max_rows,output_dir,Direct SVM Independent Accuracy,Direct SVM Independent Macro F1
0,0,full,full_20260504_154912,administrative_win_lose_mixed,administrative_win_lose_mixed,False,with_leakage,bow,../artifacts/features/dtm\administrative_win_l...,NaN,...,"['Majority Class', 'BOW + SVM']",independent_validation_macro_f1,10000,0.2500,full,full_20260504_154912,None,../artifacts/reports\administrative_win_lose_m...,0.844896,0.402306
1,0,full,full_20260504_154912,administrative_win_lose_mixed,administrative_win_lose_mixed,False,with_leakage,tf,../artifacts/features/dtm\administrative_win_l...,NaN,...,"['Majority Class', 'TF + SVM']",independent_validation_macro_f1,5000,2.0000,full,full_20260504_154912,None,../artifacts/reports\administrative_win_lose_m...,0.877596,0.334476
2,0,full,full_20260504_154912,administrative_win_lose_mixed,administrative_win_lose_mixed,False,with_leakage,tfidf,../artifacts/features/dtm\administrative_win_l...,NaN,...,"['Majority Class', 'TFIDF + SVM']",independent_validation_macro_f1,10000,4.0000,full,full_20260504_154912,None,../artifacts/reports\administrative_win_lose_m...,0.857711,0.380299
3,0,full,full_20260504_154912,administrative_win_lose_mixed,administrative_win_lose_mixed,True,no_leakage,bow,../artifacts/features/dtm\administrative_win_l...,NaN,...,"['Majority Class', 'BOW + SVM']",independent_validation_macro_f1,3000,4.0000,full,full_20260504_154912,None,../artifacts/reports\administrative_win_lose_m...,0.830756,0.380459
4,0,full,full_20260504_154912,administrative_win_lose_mixed,administrative_win_lose_mixed,True,no_leakage,tf,../artifacts/features/dtm\administrative_win_l...,NaN,...,"['Majority Class', 'TF + SVM']",independent_validation_macro_f1,3000,4.0000,full,full_20260504_154912,None,../artifacts/reports\administrative_win_lose_m...,0.877154,0.341195
5,0,full,full_20260504_154912,administrative_win_lose_mixed,administrative_win_lose_mixed,True,no_leakage,tfidf,../artifacts/features/dtm\administrative_win_l...,NaN,...,"['Majority Class', 'TFIDF + SVM']",independent_validation_macro_f1,3000,4.0000,full,full_20260504_154912,None,../artifacts/reports\administrative_win_lose_m...,0.869200,0.375332
6,0,full,full_20260504_154912,civil_win_lose_mixed,civil_win_lose_mixed,False,with_leakage,bow,../artifacts/features/dtm\civil_win_lose_mixed...,NaN,...,"['Majority Class', 'BOW + SVM']",independent_validation_macro_f1,5000,0.5000,full,full_20260504_154912,None,../artifacts/reports\civil_win_lose_mixed\with...,0.639011,0.407769
7,0,full,full_20260504_154912,civil_win_lose_mixed,civil_win_lose_mixed,False,with_leakage,tf,../artifacts/features/dtm\civil_win_lose_mixed...,NaN,...,"['Majority Class', 'TF + SVM']",independent_validation_macro_f1,10000,2.0000,full,full_20260504_154912,None,../artifacts/reports\civil_win_lose_mixed\with...,0.680494,0.404731
8,0,full,full_20260504_154912,civil_win_lose_mixed,civil_win_lose_mixed,False,with_leakage,tfidf,../artifacts/features/dtm\civil_win_lose_mixed...,NaN,...,"['Majority Class', 'TFIDF + SVM']",independent_validation_macro_f1,10000,4.0000,full,full_20260504_154912,None,../artifacts/reports\civil_win_lose_mixed\with...,0.670786,0.424841
9,0,full,full_20260504_154912,civil_win_lose_mixed,civil_win_lose_mixed,True,no_leakage,bow,../artifacts/features/dtm\civil_win_lose_mixed...,NaN,...,"['Majority Class', 'BOW + SVM']",independent_validation_macro_f1,10000,0.2500,full,full_20260504_154912,None,../artifacts/reports\civil_win_lose_mixed\no_l...,0.637246,0.402754
10,0,full,full_20260504_154912,civil_win_lose_mixed,civil_win_lose_mixed,True,no_leakage,tf,../artifacts/features/dtm\civil_win_lose_mixed...,NaN,...,"['Majority Class', 'TF + SVM']",independent_validation_macro_f1,3000,4.0000,full,full_20260504_154912,None,../artifacts/reports\civil_win_lose_mixed\no_l...,0.687555,0.417098
11,0,full,full_20260504_154912,civil_win_lose_mixed,civil_win_lose_mixed,True,no_leakage,tfidf,../artifacts/features/dtm\civil_win_lose_mixed...,NaN,...,"['Majority Class', 'TFIDF + SVM']",independent_validation_macro_f1,5000,4.0000,full,full_20260504_154912,None,../artifacts/reports\civil_win_lose_mixed\no_l...,0.679612,0.427797
12,0,full,full_20260504_154912,criminal_win_lose_mixed,criminal_win_lose_mixed,False,with_leakage,bow,../artifacts/features/dtm\criminal_win_lose_mi...,NaN,...,"['Majority Class', 'BOW + SVM']",independent_validation_macro_f1,1000,0.5000,full,full_20260504_154912,None,../artifacts/reports\criminal_win_lose_mixed\w...,0.952745,0.564200
13,0,full,full_20260504_154912,criminal_win_lose_mixed,criminal_win_lose_mixed,False,with_leakage,tf,../artifacts/features/dtm\criminal_win_lose_mi...,NaN,...,"['Majority Class', 'TF + SVM']",independent_validation_macro_f1,5000,4.0000,full,full_20260504_154912,None,../artifacts/reports\criminal_win_lose_mixed\w...,0.951980,0.526339
14,0,full,full_20260504_154912,criminal_win_lose_mixed,criminal_win_lose_mixed,False,with_leakage,tfidf,../artifacts/features/dtm\criminal_win_lose_mi...,NaN,...,"['Majority Class', 'TFIDF + SVM']",independent_validation_macro_f1,1000,4.0000,full,full_20260504_154912,None,../artifacts/reports\criminal_win_lose_mixed\w...,0.942606,0.559827
15,0,full,full_20260504_154912,criminal_win_lose_mixed,criminal_win_lose_mixed,True,no_leakage,bow,../artifacts/features/dtm\criminal_win_lose_mi...,NaN,...,"['Majority Class', 'BOW + SVM']",independent_validation_macro_f1,1000,1.0000,full,full_20260504_154912,None,../artifacts/reports\criminal_win_lose_mixed\n...,0.952554,0.563682
16,0,full,full_20260504_154912,criminal_win_lose_mixed,criminal_win_lose_mixed,True,no_leakage,tf,../artifacts/features/dtm\criminal_win_lose_mi...,NaN,...,"['Majority Class', 'TF + SVM']",independent_validation_macro_f1,5000,4.0000,full,full_20260504_154912,None,../artifacts/reports\criminal_win_lose_mixed\n...,0.951406,0.577270
17,0,full,full_20260504_154912,criminal_win_lose_mixed,criminal_win_lose_mixed,True,no_leakage,tfidf,../artifacts/features/dtm\criminal_win_lose_mi...,NaN,...,"['Majority Class', 'TFIDF + SVM']",independent_validation_macro_f1,1000,4.0000,full,full_20260504_154912,None,../artifacts/reports\criminal_win_lose_mixed\n...,0.942606,0.562174
18,0,full,full_20260504_154912,cwc_win_lose_mixed,cwc_win_lose_mixed,False,with_leakage,bow,../artifacts/features/dtm\cwc_win_lose_mixed\w...,NaN,...,"['Majority Class', 'BOW + SVM']",independent_validation_macro_f1,3000,0.2500,full,full_20260504_154912,None,../artifacts/reports\cwc_win_lose_mixed\with_l...,0.853591,0.646023
19,0,full,full_20260504_154912,cwc_win_lose_mixed,cwc_win_lose_mixed,False,with_leakage,tf,../artifacts/features/dtm\cwc_win_lose_mixed\w...,NaN,...,"['Majority Class', 'TF + SVM']",independent_validation_macro_f1,5000,4.0000,full,full_20260504_154912,None,../artifacts/reports\cwc_win_lose_mixed\with_l...,0.870166,0.581853
20,0,full,full_20260504_154912,cwc_win_lose_mixed,cwc_win_lose_mixed,False,with_leakage,tfidf,../artifacts/features/dtm\cwc_win_lose_mixed\w...,NaN,...,"['Majority Class', 'TFIDF + SVM']",independent_validation_macro_f1,5000,2.0000,full,full_20260504_154912,None,../artifacts/reports\cwc_win_lose_mixed\with_l...,0.881215,0.589811
21,0,full,full_20260504_154912,cwc_win_lose_mixed,cwc_win_lose_mixed,True,no_leakage,bow,../artifacts/features/dtm\cwc_win_lose_mixed\n...,NaN,...,"['Majority Class', 'BOW + SVM']",independent_validation_macro_f1,3000,0.0625,full,full_20260504_154912,None,../artifacts/reports\cwc_win_lose_mixed\no_lea...,0.853591,0.654139
22,0,full,full_20260504_154912,cwc_win_lose_mixed,cwc_win_lose_mixed,True,no_leakage,tf,../artifacts/features/dtm\cwc_win_lose_mixed\n...,NaN,...,"['Majority Class', 'TF + SVM']",independent_validation_macro_f1,3000,2.0000,full,full_20260504_154912,None,../artifacts/reports\cwc_win_lose_mixed\no_lea...,0.867403,0.579693
23,0,full,full_20260504_154912,cwc_win_lose_mixed,cwc_win_lose_mixed,True,no_leakage,tfidf,../artifacts/features/dtm\cwc_win_lose_mixed\n...,NaN,...,"['Majority Class', 'TFIDF + SVM']",independent_validation_macro_f1,5000,0.5000,full,full_20260504_154912,None,../artifacts/reports\cwc_win_lose_mixed\no_lea...,0.856354,0.571560

### Step 5: Keyword SHAP for Direct SVM

This section maps the selected chi-square DTM columns back to keywords, then computes linear SHAP-style keyword contributions for the Direct SVM model. It uses the patched Direct SVM summary when available, so the displayed keywords match the independently tuned Direct SVM configuration.

In [11]:
# Step 5.1 Keyword SHAP-style explanations for Direct SVM
# Pick one completed experiment here.
SHAP_DATASET_NAME = "civil_win_lose_mixed"
SHAP_REMOVE_LEAKAGE = True
SHAP_REPRESENTATION = "tfidf"  # "bow", "tf", or "tfidf"
SHAP_TOP_N = 30
SHAP_CLASS_LABEL = None  # None uses the first SVM class; or set "Win", "Lose", "Mixed"

from utils.keyword_shap import keyword_linear_shap_direct_svm

keyword_shap = keyword_linear_shap_direct_svm(
    SHAP_DATASET_NAME,
    SHAP_REMOVE_LEAKAGE,
    SHAP_REPRESENTATION,
    top_n=SHAP_TOP_N,
    class_label=SHAP_CLASS_LABEL,
    features_folder=FEATURES_FOLDER,
    artifacts_folder=ARTIFACTS_FOLDER
)
display(keyword_shap)

ValueError: Vocabulary length (24391) does not match DTM columns (24425).

### Step 6: MNIR + SVM SHAP-style explanations

This section explains the MNIR + SVM baseline. `mnir_feature_shap_svm` explains the actual MNIR z features used by SVM and does not require rerunning MNIR. `mnir_projected_keyword_importance` tries to read `mnir_mnlm.rds` and project the MNIR + SVM weights back to selected keywords; it requires Rscript/R_HOME to be available.

In [ ]:
# Step 6.1 MNIR + SVM projected token explanations
# Pick one completed MNIR + SVM experiment here.
MNIR_SHAP_DATASET_NAME = "cwc_win_lose_mixed"
MNIR_SHAP_REMOVE_LEAKAGE = True
MNIR_SHAP_REPRESENTATION = "tfidf"  # "bow", "tf", or "tfidf"
MNIR_SHAP_TOP_N = 30
MNIR_SHAP_CLASS_LABEL = None  # None uses the first SVM class; or set "Win", "Lose", "Mixed"
MNIR_SHAP_RUN_TAG = None  # None prefers the latest full run; or set e.g. "full_20260504_154912"
MNIR_SHOW_Z_FEATURE_DEBUG = False  # Set True only if you want to inspect mnir_z_* features.

from utils.keyword_shap import mnir_feature_shap_svm, mnir_projected_keyword_importance, r_runtime_diagnostic

try:
    mnir_keyword_importance = mnir_projected_keyword_importance(
        MNIR_SHAP_DATASET_NAME,
        MNIR_SHAP_REMOVE_LEAKAGE,
        MNIR_SHAP_REPRESENTATION,
        top_n=MNIR_SHAP_TOP_N,
        class_label=MNIR_SHAP_CLASS_LABEL,
        features_folder=FEATURES_FOLDER,
        artifacts_folder=ARTIFACTS_FOLDER,
        mnir_features_folder=MNIR_FEATURES_FOLDER,
        run_tag=MNIR_SHAP_RUN_TAG,
    )
    display(mnir_keyword_importance)
except Exception as exc:
    print("MNIR projected token importance is not available yet:", exc)
    print("R runtime diagnostic:", r_runtime_diagnostic())

if MNIR_SHOW_Z_FEATURE_DEBUG:
    mnir_z_shap = mnir_feature_shap_svm(
        MNIR_SHAP_DATASET_NAME,
        MNIR_SHAP_REMOVE_LEAKAGE,
        MNIR_SHAP_REPRESENTATION,
        top_n=MNIR_SHAP_TOP_N,
        class_label=MNIR_SHAP_CLASS_LABEL,
        features_folder=FEATURES_FOLDER,
        artifacts_folder=ARTIFACTS_FOLDER,
        mnir_features_folder=MNIR_FEATURES_FOLDER,
        run_tag=MNIR_SHAP_RUN_TAG,
    )
    display(mnir_z_shap)